[package]
name = "starbound-modpack-launcher"
version = "0.25.1"
description = "Grayles starbound launcher"
authors = ["base10"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.4.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.4.1", features = ["api-all"] }
preferences = "1.1.0"
rfd = "0.10.0"
reqwest = { version = "0.11.14", features = ["stream"] }
futures-util = "0.3.25"
sha2 = "0.10.6"
bytesize = "1.2.0"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
